language: node_js
node_js:
  - 12.8.0

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests. Yes there will be tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  # Tagging
  - docker tag udagram-reverseproxy thanhpham923/udagram-reverseproxy:v4a
  - docker tag udagram-api-feed thanhpham923/udagram-api-feed:v4a
  - docker tag udagram-api-user thanhpham923/udagram-api-user:v4a
  - docker tag udagram-frontend thanhpham923/udagram-frontend:local

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thanhpham923/udagram-reverseproxy:v4a
  - docker push thanhpham923/udagram-api-feed:v4a
  - docker push thanhpham923/udagram-api-user:v4a
  - docker push thanhpham923/udagram-frontend:local
